# Generated by Django 5.2 on 2025-05-13 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('current_participant', models.IntegerField(default=0)),
                ('max_participant', models.IntegerField()),
                ('status', models.CharField(choices=[('inProgress', '모집 중'), ('done', '마감'), ('canceled', '취소')], default='inProgress', max_length=10)),
                ('category', models.CharField(choices=[('tour', '여행'), ('eating', '맛집'), ('exercise', '운동'), ('else', '기타')], max_length=10)),
                ('background_pic', models.CharField(blank=True, max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetups', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_lightnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
