# Generated by Django 5.2 on 2025-06-02 15:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import lightning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=lightning.models.get_default_end_time)),
                ('current_participant', models.IntegerField(default=0)),
                ('max_participant', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('status', models.CharField(choices=[('inProgress', '모집 중'), ('done', '마감'), ('canceled', '취소')], default='inProgress', max_length=10)),
                ('category', models.CharField(choices=[('travel', '여행'), ('foodie', '맛집'), ('workout', '운동'), ('others', '기타')], default='travel', max_length=10)),
                ('gender', models.CharField(choices=[('all', '모두'), ('male', '남자만'), ('female', '여자만')], default='all', max_length=10)),
                ('background_pic', models.CharField(blank=True, max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetups', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='joined_lightnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
