# Generated by Django 5.2 on 2025-05-27 04:31

import lightning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightning',
            name='end_time',
            field=models.DateTimeField(default=lightning.models.get_default_end_time),
        ),
    ]
