# Generated by Django 5.2 on 2025-05-27 15:38

import lightning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightning',
            name='gender',
            field=models.CharField(choices=[('all', '모두'), ('male', '남자만'), ('female', '여자만')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='category',
            field=models.CharField(choices=[('travel', '여행'), ('foodie', '맛집'), ('workout', '운동'), ('others', '기타')], default='travel', max_length=10),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='end_time',
            field=models.DateTimeField(default=lightning.models.get_default_end_time),
        ),
    ]
