# Generated by Django 5.2 on 2025-06-02 15:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import lightning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lightning',
            name='gender',
            field=models.CharField(choices=[('all', '모두'), ('male', '남자만'), ('female', '여자만')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='lightning',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='lightning',
            name='meeting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='category',
            field=models.CharField(choices=[('travel', '여행'), ('foodie', '맛집'), ('workout', '운동'), ('others', '기타')], default='travel', max_length=10),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='end_time',
            field=models.DateTimeField(default=lightning.models.get_default_end_time),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='max_participant',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='participants',
            field=models.ManyToManyField(related_name='joined_lightnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
