# Generated by Django 5.2 on 2025-06-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0002_lightning_gender_lightning_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightning',
            name='status',
            field=models.CharField(choices=[('inProgress', '모집 중'), ('done', '마감'), ('canceled', '취소'), ('finished', '종료')], default='inProgress', max_length=10),
        ),
    ]
