# Generated by Django 5.2 on 2025-05-12 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0002_rename_meetup_lightning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lightning',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_lightnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
