# Generated by Django 5.2 on 2025-05-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0002_alter_lightning_end_time'),
        ('lightning', '0002_lightning_gender_alter_lightning_category_and_more'),
    ]

    operations = [
    ]
