# Generated by Django 5.2 on 2025-05-28 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0003_merge_20250528_1134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lightning',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lightning',
            name='meeting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lightning',
            name='max_participant',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='LightningParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_tag', models.CharField(choices=[('hosted', '생성한 채팅방'), ('participated', '참가한 채팅방'), ('irrelevant', '관련 없음')], default='irrelevant', max_length=20)),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.lightning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lightning',
            name='participants',
            field=models.ManyToManyField(related_name='joined_lightnings', through='lightning.LightningParticipation', to=settings.AUTH_USER_MODEL),
        ),
    ]
