# Generated by Django 5.2 on 2025-05-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0005_alter_lightning_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightning',
            name='is_active',
        ),
    ]
