# Generated by Django 5.2 on 2025-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0006_remove_lightning_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightning',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
