# Generated by Django 5.2 on 2025-06-02 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0008_alter_lightning_max_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightning',
            name='max_participant',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
