# Generated by Django 5.2 on 2025-06-02 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0010_alter_lightning_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightning',
            name='participants',
            field=models.ManyToManyField(related_name='joined_lightnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LightningParticipation',
        ),
    ]
