# Generated by Django 5.2 on 2025-05-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=50)),
                ('ttb', models.CharField(max_length=20)),
                ('tts', models.CharField(max_length=20)),
                ('deal_bas_r', models.CharField(max_length=20)),
                ('bkpr', models.CharField(max_length=20)),
                ('y_efee_r', models.CharField(max_length=20)),
                ('ten_d_efee_r', models.CharField(max_length=20)),
                ('kftc_deal_bas_r', models.CharField(max_length=20)),
                ('kftc_bkpr', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
