# Generated by Django 5.2 on 2025-05-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
    ]
