# Generated by Django 5.2 on 2025-05-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('cur_unit', 'date')},
        ),
    ]
