# Generated by Django 5.2 on 2025-05-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20250525_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangememo',
            old_name='foreign_amount',
            new_name='from_amount',
        ),
        migrations.RenameField(
            model_name='exchangememo',
            old_name='foreign_currency',
            new_name='from_currency',
        ),
        migrations.RenameField(
            model_name='exchangememo',
            old_name='krw_amount',
            new_name='to_amount',
        ),
        migrations.AddField(
            model_name='exchangememo',
            name='to_currency',
            field=models.CharField(default='KRW', max_length=10),
            preserve_default=False,
        ),
    ]
