# Generated by Django 5.2 on 2025-05-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_exchangerate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(),
        ),
    ]
