# Generated by Django 5.2 on 2025-05-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_noti', models.BooleanField(default=True)),
                ('comment_noti', models.BooleanField(default=True)),
                ('meetup_noti', models.BooleanField(default=True)),
                ('chat_noti', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('restriction_type', models.CharField(choices=[('comment_ban', 'Comment Ban'), ('post_ban', 'Post Ban'), ('meetup_ban', 'Meetup Participation Ban')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='None: Permanently ban', null=True)),
                ('release_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
