# Generated by Django 5.2 on 2025-06-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_blockuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notisetting',
            old_name='post_noti',
            new_name='reply_noti',
        ),
    ]
