# Generated by Django 5.2 on 2025-06-04 06:26

import SWAY_back.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_changed',
            field=models.ImageField(blank=True, null=True, storage=SWAY_back.storages.MediaStorage(), upload_to='media/profile_images/'),
        ),
    ]
