# Generated by Django 5.2 on 2025-05-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
