# Generated by Django 5.2 on 2025-05-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_parent_id_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='board_images/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.board')),
            ],
        ),
    ]
