# Generated by Django 5.2 on 2025-05-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_comment_parent_comment_parent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
