# Generated by Django 5.2 on 2025-05-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_rename_parent_id_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
