# Generated by Django 5.2 on 2025-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_comment_is_deleted_alter_board_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/board_images/'),
        ),
    ]
