# Generated by Django 5.2 on 2025-06-02 03:14

import SWAY_back.storages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_boardimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=SWAY_back.storages.MediaStorage(), upload_to='media/board_images/'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlikes', to='board.comment'),
        ),
    ]
