name: Daily Exchange Rate Fetch

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cloudtype fetch API
        run: |
          curl -X GET "https://port-0-sway-server-mam72goke080404a.sel4.cloudtype.app/currency/fetch/daily/"